### ISSUE TITLE
Great work thanks, can you give any advice on why intellisense is not working

### ISSUE THREAD

**Issue by jasperza** [rickkas7/visual-studio-for-particle#1]
I followed the instructions and it compiles in and uploads the firmware directly to the attached photon by DFU, thank you so much! this alone will save me hundreds of hours over the next few years!!
My intellisense is not working, it would be good to have this working, that will save me  a few more hundred hours. Any tips would be appreciated.

Intellisense is completely broken on the "folder" type VS project:
![image](https://user-images.githubusercontent.com/12615954/45208043-ef4f1080-b289-11e8-948f-fc471af39952.png)

note when I open a new project in VS for example, a Raspberry project, Intellisense works:
![image](https://user-images.githubusercontent.com/12615954/45208323-95027f80-b28a-11e8-8c15-d76fbf8767e9.png)

Heres my src folder:
![image](https://user-images.githubusercontent.com/12615954/45208178-45bc4f00-b28a-11e8-94f2-9b2aa1115f13.png)

**Comment by jasperza** [comment]
Forget the above. For some reason it magically came right, after I created that Rasberry project and went back to the tinker project , intellisense started working: 
![image](https://user-images.githubusercontent.com/12615954/45208577-34277700-b28b-11e8-9611-fafd882943db.png)

**Comment by rickkas7** [comment]
The most common reason is that the firmware source and the gcc-arm includes are in a different directory. The example assumes they're in a peer directory to your source directory. If they're in a different directory, you can edit CppProperties.json to be the actual path. It may be easier to make it an absolute path.
