### ISSUE TITLE
Help using libraries

### ISSUE THREAD

**Issue by jasperza** [rickkas7/visual-studio-for-particle#2]
I get build errors when trying to use other libraries.

I have placed the relayshield library in the lib folder, and included the paths to the libraries in cppproperties.json. Intellisense works for the libraries but I am getting build errors:

![image](https://user-images.githubusercontent.com/12615954/45216093-b02bba00-b29f-11e8-9c0b-705ea7a49b4f.png)

Note that I had to manually copy the library into my folder after using "particle library view RelayShield" becuase "particle library copy RelayShield" gave a "..library not found in directory .." error. Not sure if this makes a difference.

**Comment by rickkas7** [comment]
The message about RelayShield_h is just a warning.

The error is on line 26 of your code mast_relays2.cpp, but without seeing the code there's no way to know the cause. It very well could be in lines before that.

**Comment by jasperza** [comment]
ok true , thanks ill dive in deeper I made a "relay Blink" program and the library works:
#include "Particle.h"
#include "lib/RelayShield/src/RelayShield.h"
RelayShield myRelays;

void setup()
{
	myRelays.begin();
}

void loop()
{
	myRelays.allOn();
	delay(1000);
	myRelays.allOff();
	delay(1000);
}

**Comment by jasperza** [comment]
the problem is in the online version of this project I am using eerpom funcs but in the local version i dont think this library is available:
EPROM.get(iEEPromAddr, eepromStore);
struct StoreStruct {
	int version ;   // This is to detect if they are your settings
